window.GAME_CONFIG = Object.freeze({
  version: "v2.1.3",
  rarityStyles: {
    STAR: { label: "STAR", color: "#ffd94d", glow: "rgba(255, 236, 112, 0.82)", particles: 34 },
    C: { label: "C", color: "#6f8798", glow: "rgba(210, 231, 238, 0.42)", particles: 8 },
    R: { label: "R", color: "#2f8fcb", glow: "rgba(111, 218, 240, 0.58)", particles: 16 },
    SR: { label: "SR", color: "#d68a18", glow: "rgba(255, 205, 84, 0.74)", particles: 28 },
    SSR: { label: "SSR", color: "#c44df2", glow: "rgba(240, 136, 255, 0.82)", particles: 40 },
  },
  rodUpgrades: [
    { id: "bamboo", name: "竹の竿", cost: 0, power: 0, biteBonus: 0, rareBonus: 0, saleBonus: 0, rodColor: "#5a3b28", accentColor: "rgba(245,229,168,0.75)", glow: 0 },
    { id: "flex", name: "しなやかな竿", cost: 160, power: 1, biteBonus: 0.1, rareBonus: 0.1, saleBonus: 0, rodColor: "#2f6f55", accentColor: "#b7f0c3", glow: 2 },
    { id: "lucky", name: "星見の竿", cost: 360, power: 1, biteBonus: 0.02, rareBonus: 0.42, saleBonus: 0, rodColor: "#37508c", accentColor: "#d8e2ff", glow: 5 },
    { id: "quick", name: "早合わせの竿", cost: 360, power: 1, biteBonus: 0.28, rareBonus: 0.08, saleBonus: 0, rodColor: "#7d8f9a", accentColor: "#f3fbff", glow: 4 },
    { id: "merchant", name: "商人の竿", cost: 360, power: 1, biteBonus: 0.08, rareBonus: 0.05, saleBonus: 0.28, rodColor: "#b97818", accentColor: "#ffe070", glow: 5 },
    { id: "master", name: "名人の竿", cost: 1100, power: 2, biteBonus: 0.24, rareBonus: 0.38, saleBonus: 0.16, rodColor: "#5b3d91", accentColor: "#ffc8ff", glow: 8 },
  ],
  floatUpgrades: [
    { id: "plain", name: "ふつうの浮き", cost: 0, nibbleBonus: 0, biteBonus: 0 },
    { id: "bright", name: "見やすい浮き", cost: 180, nibbleBonus: 0.18, biteBonus: 0.04 },
    { id: "signal", name: "合図の浮き", cost: 460, nibbleBonus: 0.28, biteBonus: 0.1 },
  ],
  reelUpgrades: [
    { id: "plain", name: "ふつうのリール", cost: 0, biteBonus: 0, saleBonus: 0 },
    { id: "smooth", name: "なめらかリール", cost: 220, biteBonus: 0.08, saleBonus: 0.04 },
    { id: "pro", name: "プロリール", cost: 620, biteBonus: 0.16, saleBonus: 0.1 },
  ],
  baitUpgrades: [
    { id: "normal", name: "ふつうのエサ", cost: 0, rarityMultiplier: { C: 1, R: 1, SR: 1, SSR: 1 }, fishBonus: {} },
    { id: "rare", name: "きらめくエサ", cost: 260, rarityMultiplier: { C: 0.82, R: 1.16, SR: 1.45, SSR: 1.18 }, fishBonus: {} },
    { id: "tuna", name: "大物エサ", cost: 520, rarityMultiplier: { C: 0.72, R: 1, SR: 1.72, SSR: 1.28 }, fishBonus: { "マグロ": 1.6, "ヌシ": 1.7 } },
  ],
  sizeTiers: [
    { label: "小", multiplier: 0.8, shadowScale: 0.88, weight: 30 },
    { label: "中", multiplier: 1, shadowScale: 1, weight: 44 },
    { label: "大", multiplier: 1.35, shadowScale: 1.18, weight: 20 },
    { label: "特大", multiplier: 2, shadowScale: 1.42, weight: 6 },
  ],
  feverSettings: {
    duration: 30,
    starWeight: 3,
    rarityMultiplier: { C: 0.38, R: 1.45, SR: 2.25, SSR: 2.8 },
    bigBonus: 0.18,
  },
  starCatch: {
    name: "星",
    points: 0,
    shadow: 42,
    speed: 74,
    biteWindow: 0.62,
    color: "#ffd94d",
    rarity: "STAR",
    catchWeight: 3,
    catchDifficulty: 1,
    isStar: true,
  },
  fishingSpots: [
    {
      id: "pier",
      name: "いつもの桟橋",
      description: "小さめの魚が多く、安定して稼ぎやすい。",
      unlockRodLevel: 0,
      rarityMultiplier: { C: 1.2, R: 0.9, SR: 0.45, SSR: 0.18 },
      bigBonus: 0,
      theme: {
        skyTop: "#86d8f0",
        skyBottom: "#eef9f6",
        waterTop: "#6ac0da",
        waterMid: "#2493c5",
        waterBottom: "#083a67",
        sun: "#ffcb58",
        cloud: "rgba(255,255,255,0.82)",
        horizon: "rgba(255,255,255,0.32)",
        detail: "pier",
      },
    },
    {
      id: "reef",
      name: "沖の岩場",
      description: "Rの魚と大きめの魚が少し増える。",
      unlockRodLevel: 1,
      rarityMultiplier: { C: 0.82, R: 1.28, SR: 0.9, SSR: 0.36 },
      bigBonus: 0.12,
      theme: {
        skyTop: "#7bcbea",
        skyBottom: "#d9f1f6",
        waterTop: "#46abc7",
        waterMid: "#147d9d",
        waterBottom: "#063b5d",
        sun: "#ffd16c",
        cloud: "rgba(240,250,255,0.76)",
        horizon: "rgba(231,248,255,0.28)",
        detail: "reef",
      },
    },
    {
      id: "deep",
      name: "深い海",
      description: "SR以上と特大が狙えるが、銀の竿以上が必要。",
      unlockRodLevel: 2,
      rarityMultiplier: { C: 0.52, R: 1, SR: 1.62, SSR: 1.96 },
      bigBonus: 0.28,
      theme: {
        skyTop: "#253b65",
        skyBottom: "#486f8f",
        waterTop: "#1d7895",
        waterMid: "#0c4d75",
        waterBottom: "#03192f",
        sun: "#d8e2ff",
        cloud: "rgba(191,211,229,0.5)",
        horizon: "rgba(170,211,232,0.22)",
        detail: "deep",
      },
    },
  ],
  bgmThemes: {
    menu: {
      tempo: 132,
      leadType: "square",
      padType: "triangle",
      leadGain: 0.032,
      padGain: 0.018,
      lead: [
        ["C5"], ["E5"], ["G5"], ["C6"], ["B5"], ["G5"], ["E5"], [],
        ["D5"], ["F5"], ["A5"], ["D6"], ["C6"], ["A5"], ["F5"], [],
      ],
      pad: [["C3"], [], ["G3"], [], ["F3"], [], ["G3"], []],
    },
    pier: {
      tempo: 92,
      leadType: "triangle",
      padType: "sine",
      leadGain: 0.04,
      padGain: 0.022,
      lead: [
        ["E5"], [], ["G5"], [], ["A5"], [], ["G5"], [],
        ["E5"], [], ["D5"], [], ["B4"], [], ["D5"], [],
      ],
      pad: [["E3"], [], ["B3"], [], ["C4"], [], ["B3"], []],
    },
    reef: {
      tempo: 108,
      leadType: "triangle",
      padType: "square",
      leadGain: 0.035,
      padGain: 0.018,
      lead: [
        ["A4"], ["C5"], ["E5"], [], ["D5"], ["E5"], ["A5"], [],
        ["G5"], ["E5"], ["D5"], [], ["C5"], ["D5"], ["E5"], [],
      ],
      pad: [["A3"], [], ["E4"], [], ["G3"], [], ["E4"], []],
    },
    deep: {
      tempo: 72,
      leadType: "sine",
      padType: "triangle",
      leadGain: 0.03,
      padGain: 0.024,
      lead: [
        ["D5"], [], [], ["A4"], [], ["F4"], [], [],
        ["E5"], [], [], ["C5"], [], ["A4"], [], [],
      ],
      pad: [["D3"], [], [], [], ["A2"], [], [], []],
    },
  },
  missionDefs: [
    { id: "catch5", label: "魚を5匹釣る", target: 5, reward: 90, kind: "count" },
    { id: "earn300", label: "魚を売って300円稼ぐ", target: 300, reward: 140, kind: "money" },
    { id: "rare1", label: "R以上の魚を1匹釣る", target: 1, reward: 180, kind: "rare" },
    { id: "catch20", label: "魚を20匹釣る", target: 20, reward: 220, kind: "count" },
    { id: "earn2000", label: "魚を売って2000円稼ぐ", target: 2000, reward: 320, kind: "money" },
    { id: "deep10", label: "深い海で10匹釣る", target: 10, reward: 340, kind: "spotCount", spotId: "deep" },
    { id: "big3", label: "特大を3匹釣る", target: 3, reward: 420, kind: "sizeCatch", sizeLabel: "特大" },
    { id: "sr5", label: "SR以上を5匹釣る", target: 5, reward: 520, kind: "rarityCount", rarity: "SR" },
    { id: "ssr1", label: "SSRを1匹釣る", target: 1, reward: 900, kind: "rarityCount", rarity: "SSR" },
    { id: "tuna2", label: "マグロを2匹釣る", target: 2, reward: 680, kind: "fishCount", fishName: "マグロ" },
    { id: "discover10", label: "図鑑を10種埋める", target: 10, reward: 760, kind: "discovered" },
    { id: "sizeComp3", label: "サイズコンプを3種達成", target: 3, reward: 980, kind: "sizeComplete" },
    { id: "legendTriplet", label: "ヌシ・コダマウオ・ネコギョを釣る", target: 3, reward: 1400, kind: "fishSet", fishNames: ["ヌシ", "コダマウオ", "ネコギョ"] },
  ],
  fishTypes: [
    { name: "ワカサギ", points: 10, shadow: 30, speed: 96, biteWindow: 0.92, color: "#dce8ec", image: "assets/fish/001.png", rarity: "C", catchWeight: 32, catchDifficulty: 0, description: "群れで泳ぐ小さな魚じゃ。動きは素直で、釣りの入り口にぴったりじゃな。", recommendedSpot: "pier", sizeHint: "小と中が多く、特大はかなり珍しいぞい。" },
    { name: "アジ", points: 20, shadow: 42, speed: 82, biteWindow: 0.82, color: "#87b8d6", image: "assets/fish/002.png", rarity: "C", catchWeight: 28, catchDifficulty: 0, description: "きびきびと泳ぐ元気者じゃ。桟橋まわりで姿を見せやすく、数も狙いやすいぞい。", recommendedSpot: "pier", sizeHint: "中が中心じゃが、大もそこそこ混ざる魚じゃ。" },
    { name: "タイ", points: 45, shadow: 58, speed: 68, biteWindow: 0.72, color: "#f17a73", image: "assets/fish/003.png", rarity: "R", catchWeight: 18, catchDifficulty: 1, description: "堂々とした魚影が目を引く一匹じゃ。焦らず合わせると、きれいに釣り上がるぞい。", recommendedSpot: "reef", sizeHint: "中と大が狙い目で、特大は岩場で望みが高まるのう。" },
    { name: "スズキ", points: 70, shadow: 76, speed: 58, biteWindow: 0.62, color: "#9fc5ba", image: "assets/fish/011.png", rarity: "R", catchWeight: 14, catchDifficulty: 1, description: "水面近くを鋭く回ることもある古参の大物じゃ。見えたら気を引き締めたいのう。", recommendedSpot: "reef", sizeHint: "大がよく似合う魚じゃ。特大を狙うなら岩場通いじゃな。" },
    { name: "マグロ", points: 110, shadow: 98, speed: 48, biteWindow: 0.54, color: "#4c73b8", image: "assets/fish/012.png", rarity: "SR", catchWeight: 7, catchDifficulty: 2, description: "海の王者と呼びたくなる迫力じゃ。浮きが沈んだ瞬間を逃さぬ者だけが手にできるぞい。", recommendedSpot: "deep", sizeHint: "大と特大の夢がある魚じゃ。深い海でこそ本領発揮じゃぞ。" },
    { name: "カワハギ", points: 65, shadow: 70, speed: 60, biteWindow: 0.66, color: "#167988", image: "assets/fish/004.png", rarity: "R", catchWeight: 13, catchDifficulty: 1, description: "ひらりと方向を変える身軽な魚じゃ。見た目よりも、間の取り方が勝負どころじゃな。", recommendedSpot: "reef", sizeHint: "小から大まで幅広いが、中サイズがいちばん落ち着くのう。" },
    { name: "マンボウ", points: 90, shadow: 88, speed: 42, biteWindow: 0.58, color: "#f7cbd8", image: "assets/fish/005.png", rarity: "SR", catchWeight: 6, catchDifficulty: 2, description: "ゆったり見えて、意外と気まぐれ。大きな魚影のわりに、出会えると少しうれしくなる魚じゃ。", recommendedSpot: "deep", sizeHint: "中でも大きく見えるが、真の狙いは大と特大じゃな。" },
    { name: "ニジイロギョ", points: 150, shadow: 92, speed: 62, biteWindow: 0.5, color: "#ff5eb8", image: "assets/fish/006.png", rarity: "SR", catchWeight: 4, catchDifficulty: 3, description: "光の加減で色が揺れるように見える珍魚じゃ。見つけても、落ち着いて狙わねば逃げるぞい。", recommendedSpot: "deep", sizeHint: "中以上が多く、特大はひときわ華やかな記録になるぞい。" },
    { name: "ヌシ", points: 220, shadow: 104, speed: 38, biteWindow: 0.44, color: "#347d9f", image: "assets/fish/007.png", rarity: "SSR", catchWeight: 1, catchDifficulty: 3, description: "その場の空気まで変える特別な魚影じゃ。釣れたなら、胸を張って自慢してよいぞい。", recommendedSpot: "deep", sizeHint: "大物ぞろいじゃ。特大の記録は、まさに語り草になるじゃろう。" },
    { name: "ハートフィッシュ", points: 85, shadow: 72, speed: 70, biteWindow: 0.64, color: "#c9f0e8", image: "assets/fish/008.png", rarity: "R", catchWeight: 10, catchDifficulty: 1, description: "愛らしい模様をもつ人気者じゃ。近づき方は素直じゃが、見とれておると機を逃すのう。", recommendedSpot: "pier", sizeHint: "小と中を集めやすい魚じゃ。大になると急に出会いが減るぞい。" },
    { name: "ムーンフィッシュ", points: 140, shadow: 90, speed: 56, biteWindow: 0.52, color: "#6d67b8", image: "assets/fish/009.png", rarity: "SR", catchWeight: 5, catchDifficulty: 2, description: "夜の海を思わせる静かな気配をまとう魚じゃ。落ち着いて待てる者ほど縁があるぞい。", recommendedSpot: "deep", sizeHint: "中から大が中心じゃが、特大はめったに姿を見せぬのう。" },
    { name: "コダマウオ", points: 185, shadow: 86, speed: 66, biteWindow: 0.46, color: "#d9d7f8", image: "assets/fish/010.png", rarity: "SSR", catchWeight: 2, catchDifficulty: 3, description: "魚なのか精霊なのか、博士にも断言できぬ不思議な存在じゃ。見つけたら幸運と思ってよい。", recommendedSpot: "deep", sizeHint: "中以上で現れやすく、特大は本当に気まぐれじゃ。" },
    { name: "タコ", points: 75, shadow: 68, speed: 64, biteWindow: 0.68, color: "#f3a5be", image: "assets/fish/013.png", rarity: "R", catchWeight: 11, catchDifficulty: 1, description: "泳ぎ方が独特で、影の見え方も少し変わっておる。海の変化球として侮れぬ相手じゃ。", recommendedSpot: "reef", sizeHint: "中サイズが集まりやすいが、大も十分狙える手応えがあるぞい。" },
    { name: "ネコギョ", points: 190, shadow: 94, speed: 54, biteWindow: 0.46, color: "#f3c28d", image: "assets/fish/014.png", rarity: "SSR", catchWeight: 2, catchDifficulty: 3, description: "見た者の多くが二度見する珍魚じゃ。魚らしさと猫らしさ、その両方を感じる妙味があるのう。", recommendedSpot: "pier", sizeHint: "小でも存在感があるが、大と特大はとくに記憶に残る釣果じゃ。" },
  ],
});
