window.GAME_CONFIG = Object.freeze({
  version: "v2.4.12",
  shinyOdds: 4096,
  rarityStyles: {
    STAR: { label: "STAR", color: "#ffd94d", glow: "rgba(255, 236, 112, 0.82)", particles: 34 },
    COMMON: { label: "コモン", color: "#6f8798", glow: "rgba(210, 231, 238, 0.42)", particles: 8 },
    UNCOMMON: { label: "アンコモン", color: "#3d9b5f", glow: "rgba(142, 229, 165, 0.5)", particles: 12 },
    RARE: { label: "レア", color: "#2f8fcb", glow: "rgba(111, 218, 240, 0.58)", particles: 16 },
    EPIC: { label: "エピック", color: "#8e65d8", glow: "rgba(178, 142, 255, 0.66)", particles: 24 },
    LEGENDARY: { label: "レジェンダリー", color: "#d68a18", glow: "rgba(255, 205, 84, 0.74)", particles: 32 },
    MYTHIC: { label: "ミシック", color: "#c44df2", glow: "rgba(240, 136, 255, 0.82)", particles: 42 },
    SECRET: { label: "シークレット", color: "#252142", glow: "rgba(255, 91, 214, 0.9)", particles: 56 },
  },
  rodUpgrades: [
    { id: "bamboo", name: "竹の竿", cost: 0, power: 0, biteBonus: 0, rareBonus: 0, saleBonus: 0, rodColor: "#5a3b28", accentColor: "rgba(245,229,168,0.75)", glow: 0 },
    { id: "flex", name: "しなやかな竿", cost: 160, power: 1, biteBonus: 0.1, rareBonus: 0.1, saleBonus: 0, rodColor: "#2f6f55", accentColor: "#b7f0c3", glow: 2 },
    { id: "lucky", name: "星見の竿", cost: 360, power: 1, biteBonus: 0.02, rareBonus: 0.42, saleBonus: 0, rodColor: "#37508c", accentColor: "#d8e2ff", glow: 5 },
    { id: "quick", name: "早合わせの竿", cost: 360, power: 1, biteBonus: 0.28, rareBonus: 0.08, saleBonus: 0, rodColor: "#7d8f9a", accentColor: "#f3fbff", glow: 4 },
    { id: "merchant", name: "商人の竿", cost: 360, power: 1, biteBonus: 0.08, rareBonus: 0.05, saleBonus: 0.28, rodColor: "#b97818", accentColor: "#ffe070", glow: 5 },
    { id: "master", name: "名人の竿", cost: 1100, power: 2, biteBonus: 0.24, rareBonus: 0.38, saleBonus: 0.16, rodColor: "#5b3d91", accentColor: "#ffc8ff", glow: 8 },
    { id: "abyss", name: "深淵の竿", cost: 3200, power: 3, biteBonus: 0.3, rareBonus: 0.62, saleBonus: 0.24, rodColor: "#20314f", accentColor: "#7ff0ff", glow: 11 },
    { id: "myth", name: "神話の竿", cost: 9000, power: 4, biteBonus: 0.38, rareBonus: 0.92, saleBonus: 0.42, rodColor: "#fff3a6", accentColor: "#ff6fd8", glow: 16 },
  ],
  floatUpgrades: [
    { id: "plain", name: "ふつうの浮き", cost: 0, nibbleBonus: 0, biteBonus: 0 },
    { id: "bright", name: "見やすい浮き", cost: 180, nibbleBonus: 0.18, biteBonus: 0.04 },
    { id: "signal", name: "合図の浮き", cost: 460, nibbleBonus: 0.28, biteBonus: 0.1 },
    { id: "crystal", name: "水晶の浮き", cost: 1250, nibbleBonus: 0.42, biteBonus: 0.16 },
    { id: "oracle", name: "予言の浮き", cost: 4200, nibbleBonus: 0.62, biteBonus: 0.24 },
  ],
  reelUpgrades: [
    { id: "plain", name: "ふつうのリール", cost: 0, biteBonus: 0, saleBonus: 0 },
    { id: "smooth", name: "なめらかリール", cost: 220, biteBonus: 0.08, saleBonus: 0.04 },
    { id: "pro", name: "プロリール", cost: 620, biteBonus: 0.16, saleBonus: 0.1 },
    { id: "gold", name: "金のリール", cost: 1650, biteBonus: 0.22, saleBonus: 0.18 },
    { id: "crown", name: "王冠リール", cost: 5600, biteBonus: 0.32, saleBonus: 0.3 },
  ],
  baitUpgrades: [
    { id: "normal", name: "ふつうのエサ", cost: 0, rarityMultiplier: { COMMON: 1, UNCOMMON: 1, RARE: 1, EPIC: 1, LEGENDARY: 1, MYTHIC: 1, SECRET: 1 }, fishBonus: {} },
    { id: "rare", name: "きらめくエサ", cost: 260, rarityMultiplier: { COMMON: 0.82, UNCOMMON: 1.04, RARE: 1.18, EPIC: 1.38, LEGENDARY: 1.22, MYTHIC: 1.1, SECRET: 0.92 }, fishBonus: {} },
    { id: "tuna", name: "大物エサ", cost: 520, rarityMultiplier: { COMMON: 0.72, UNCOMMON: 0.94, RARE: 1.08, EPIC: 1.58, LEGENDARY: 1.42, MYTHIC: 1.2, SECRET: 0.96 }, fishBonus: { "マグロ": 1.6, "ヌシ": 1.7 } },
    { id: "legend", name: "伝説のエサ", cost: 1800, rarityMultiplier: { COMMON: 0.45, UNCOMMON: 0.72, RARE: 0.95, EPIC: 1.38, LEGENDARY: 2.05, MYTHIC: 2.35, SECRET: 1.55 }, fishBonus: { "コダマウオ": 1.45, "ネコギョ": 1.45, "ホシクジラ": 1.7 } },
    { id: "abyss", name: "深淵のエサ", cost: 4200, rarityMultiplier: { COMMON: 0.28, UNCOMMON: 0.48, RARE: 0.74, EPIC: 1.18, LEGENDARY: 1.72, MYTHIC: 2.6, SECRET: 3.4 }, fishBonus: { "アビスドラゴン": 2, "トキノサカナ": 1.8 } },
  ],
  sizeTiers: [
    { label: "小", multiplier: 0.8, shadowScale: 0.88, weight: 30 },
    { label: "中", multiplier: 1, shadowScale: 1, weight: 44 },
    { label: "大", multiplier: 1.35, shadowScale: 1.18, weight: 20 },
    { label: "特大", multiplier: 2, shadowScale: 1.42, weight: 6 },
  ],
  feverSettings: {
    duration: 30,
    starWeight: 3,
    rarityMultiplier: { COMMON: 0.38, UNCOMMON: 0.86, RARE: 1.42, EPIC: 1.85, LEGENDARY: 2.25, MYTHIC: 2.7, SECRET: 3.15 },
    bigBonus: 0.18,
  },
  starCatch: {
    name: "星",
    points: 0,
    shadow: 42,
    speed: 74,
    biteWindow: 0.62,
    color: "#ffd94d",
    rarity: "STAR",
    catchWeight: 3,
    catchDifficulty: 1,
    isStar: true,
  },
  fishingSpots: [
    {
      id: "pier",
      name: "いつもの桟橋",
      description: "小さめの魚が多く、安定して稼ぎやすい。",
      unlockRodLevel: 0,
      rarityMultiplier: { COMMON: 1.2, UNCOMMON: 1.05, RARE: 0.8, EPIC: 0.42, LEGENDARY: 0.24, MYTHIC: 0.14, SECRET: 0.08 },
      bigBonus: 0,
      theme: {
        skyTop: "#86d8f0",
        skyBottom: "#eef9f6",
        waterTop: "#6ac0da",
        waterMid: "#2493c5",
        waterBottom: "#083a67",
        sun: "#ffcb58",
        cloud: "rgba(255,255,255,0.82)",
        horizon: "rgba(255,255,255,0.32)",
        detail: "pier",
      },
    },
    {
      id: "reef",
      name: "沖の岩場",
      description: "レアの魚と大きめの魚が少し増える。",
      unlockRodLevel: 1,
      rarityMultiplier: { COMMON: 0.82, UNCOMMON: 1.18, RARE: 1.28, EPIC: 0.86, LEGENDARY: 0.52, MYTHIC: 0.28, SECRET: 0.14 },
      bigBonus: 0.12,
      theme: {
        skyTop: "#7bcbea",
        skyBottom: "#d9f1f6",
        waterTop: "#46abc7",
        waterMid: "#147d9d",
        waterBottom: "#063b5d",
        sun: "#ffd16c",
        cloud: "rgba(240,250,255,0.76)",
        horizon: "rgba(231,248,255,0.28)",
        detail: "reef",
      },
    },
    {
      id: "estuary",
      name: "夕焼け河口",
      description: "アンコモンからエピックまでがほどよく混ざり、夕暮れの魚影が見えやすい。しなやかな竿以上が必要。",
      unlockRodLevel: 1,
      rarityMultiplier: { COMMON: 0.78, UNCOMMON: 1.22, RARE: 1.14, EPIC: 1.08, LEGENDARY: 0.68, MYTHIC: 0.34, SECRET: 0.16 },
      bigBonus: 0.18,
      theme: {
        skyTop: "#f08a62",
        skyBottom: "#ffe3a3",
        waterTop: "#df8e67",
        waterMid: "#9d6f7d",
        waterBottom: "#17314f",
        sun: "#fff08a",
        cloud: "rgba(255,238,196,0.72)",
        horizon: "rgba(255,216,151,0.42)",
        detail: "estuary",
      },
    },
    {
      id: "deep",
      name: "深い海",
      description: "エピック以上と特大が狙えるが、銀の竿以上が必要。",
      unlockRodLevel: 2,
      rarityMultiplier: { COMMON: 0.52, UNCOMMON: 0.78, RARE: 1, EPIC: 1.42, LEGENDARY: 1.72, MYTHIC: 1.86, SECRET: 1.18 },
      bigBonus: 0.28,
      theme: {
        skyTop: "#253b65",
        skyBottom: "#486f8f",
        waterTop: "#1d7895",
        waterMid: "#0c4d75",
        waterBottom: "#03192f",
        sun: "#d8e2ff",
        cloud: "rgba(191,211,229,0.5)",
        horizon: "rgba(170,211,232,0.22)",
        detail: "deep",
      },
    },
    {
      id: "abyss",
      name: "幻の海溝",
      description: "ミシックやシークレットと特大を本気で狙う終盤の海。深淵の竿以上が必要。",
      unlockRodLevel: 3,
      rarityMultiplier: { COMMON: 0.28, UNCOMMON: 0.44, RARE: 0.72, EPIC: 1.18, LEGENDARY: 1.84, MYTHIC: 2.65, SECRET: 3.45 },
      bigBonus: 0.42,
      theme: {
        skyTop: "#121b35",
        skyBottom: "#2f4b66",
        waterTop: "#135d78",
        waterMid: "#073553",
        waterBottom: "#010a19",
        sun: "#b6fff5",
        cloud: "rgba(164,198,220,0.28)",
        horizon: "rgba(126,238,255,0.2)",
        detail: "abyss",
      },
    },
  ],
  bgmThemes: {
    menu: {
      tempo: 132,
      leadType: "square",
      padType: "triangle",
      leadGain: 0.032,
      padGain: 0.018,
      lead: [
        ["C5"], ["E5"], ["G5"], ["C6"], ["B5"], ["G5"], ["E5"], [],
        ["D5"], ["F5"], ["A5"], ["D6"], ["C6"], ["A5"], ["F5"], [],
      ],
      pad: [["C3"], [], ["G3"], [], ["F3"], [], ["G3"], []],
    },
    pier: {
      tempo: 92,
      leadType: "triangle",
      padType: "sine",
      leadGain: 0.04,
      padGain: 0.022,
      lead: [
        ["E5"], [], ["G5"], [], ["A5"], [], ["G5"], [],
        ["E5"], [], ["D5"], [], ["B4"], [], ["D5"], [],
      ],
      pad: [["E3"], [], ["B3"], [], ["C4"], [], ["B3"], []],
    },
    reef: {
      tempo: 108,
      leadType: "triangle",
      padType: "square",
      leadGain: 0.035,
      padGain: 0.018,
      lead: [
        ["A4"], ["C5"], ["E5"], [], ["D5"], ["E5"], ["A5"], [],
        ["G5"], ["E5"], ["D5"], [], ["C5"], ["D5"], ["E5"], [],
      ],
      pad: [["A3"], [], ["E4"], [], ["G3"], [], ["E4"], []],
    },
    estuary: {
      tempo: 100,
      leadType: "triangle",
      padType: "sine",
      leadGain: 0.034,
      padGain: 0.023,
      lead: [
        ["G4"], [], ["B4"], ["D5"], [], ["E5"], ["D5"], [],
        ["A4"], [], ["C5"], ["E5"], [], ["D5"], ["B4"], [],
      ],
      pad: [["G3"], [], ["D4"], [], ["E3"], [], ["C4"], []],
    },
    deep: {
      tempo: 72,
      leadType: "sine",
      padType: "triangle",
      leadGain: 0.03,
      padGain: 0.024,
      lead: [
        ["D5"], [], [], ["A4"], [], ["F4"], [], [],
        ["E5"], [], [], ["C5"], [], ["A4"], [], [],
      ],
      pad: [["D3"], [], [], [], ["A2"], [], [], []],
    },
    abyss: {
      tempo: 84,
      leadType: "sine",
      padType: "sine",
      leadGain: 0.032,
      padGain: 0.026,
      lead: [
        ["F5"], [], ["C5"], [], ["G5"], [], [], ["D5"],
        ["A5"], [], ["E5"], [], ["C6"], [], ["G5"], [],
      ],
      pad: [["F2"], [], [], ["C3"], [], [], ["D3"], []],
    },
  },
  missionDefs: [
    { id: "catch5", label: "魚を5匹釣る", target: 5, reward: 90, kind: "count" },
    { id: "earn300", label: "魚を売って300円稼ぐ", target: 300, reward: 140, kind: "money" },
    { id: "rare1", label: "レア以上の魚を1匹釣る", target: 1, reward: 180, kind: "rare" },
    { id: "catch20", label: "魚を20匹釣る", target: 20, reward: 220, kind: "count" },
    { id: "earn2000", label: "魚を売って2000円稼ぐ", target: 2000, reward: 320, kind: "money" },
    { id: "deep10", label: "深い海で10匹釣る", target: 10, reward: 340, kind: "spotCount", spotId: "deep" },
    { id: "big3", label: "特大を3匹釣る", target: 3, reward: 420, kind: "sizeCatch", sizeLabel: "特大" },
    { id: "sr5", label: "エピック以上を5匹釣る", target: 5, reward: 520, kind: "rarityCount", rarity: "EPIC" },
    { id: "ssr1", label: "ミシック以上を1匹釣る", target: 1, reward: 900, kind: "rarityCount", rarity: "MYTHIC" },
    { id: "tuna2", label: "マグロを2匹釣る", target: 2, reward: 680, kind: "fishCount", fishName: "マグロ" },
    { id: "discover10", label: "図鑑を10種埋める", target: 10, reward: 760, kind: "discovered" },
    { id: "sizeComp3", label: "サイズコンプを3種達成", target: 3, reward: 980, kind: "sizeComplete" },
    { id: "legendTriplet", label: "ヌシ・コダマウオ・ネコギョを釣る", target: 3, reward: 1400, kind: "fishSet", fishNames: ["ヌシ", "コダマウオ", "ネコギョ"] },
    { id: "catch100", label: "魚を100匹釣る", target: 100, reward: 1600, kind: "count" },
    { id: "catch300", label: "魚を300匹釣る", target: 300, reward: 5200, kind: "count" },
    { id: "earn30000", label: "魚を売って30000円稼ぐ", target: 30000, reward: 3600, kind: "money" },
    { id: "earn100000", label: "魚を売って100000円稼ぐ", target: 100000, reward: 12000, kind: "money" },
    { id: "reef50", label: "沖の岩場で50匹釣る", target: 50, reward: 1800, kind: "spotCount", spotId: "reef" },
    { id: "estuary50", label: "夕焼け河口で50匹釣る", target: 50, reward: 2200, kind: "spotCount", spotId: "estuary" },
    { id: "deep50", label: "深い海で50匹釣る", target: 50, reward: 2600, kind: "spotCount", spotId: "deep" },
    { id: "abyss30", label: "幻の海溝で30匹釣る", target: 30, reward: 4200, kind: "spotCount", spotId: "abyss" },
    { id: "big20", label: "特大を20匹釣る", target: 20, reward: 2400, kind: "sizeCatch", sizeLabel: "特大" },
    { id: "big80", label: "特大を80匹釣る", target: 80, reward: 9800, kind: "sizeCatch", sizeLabel: "特大" },
    { id: "sr25", label: "エピック以上を25匹釣る", target: 25, reward: 3200, kind: "rarityCount", rarity: "EPIC" },
    { id: "sr100", label: "エピック以上を100匹釣る", target: 100, reward: 11000, kind: "rarityCount", rarity: "EPIC" },
    { id: "ssr5", label: "ミシック以上を5匹釣る", target: 5, reward: 4800, kind: "rarityCount", rarity: "MYTHIC" },
    { id: "ssr20", label: "ミシック以上を20匹釣る", target: 20, reward: 18000, kind: "rarityCount", rarity: "MYTHIC" },
    { id: "coelacanth3", label: "シーラカンスを3匹釣る", target: 3, reward: 4400, kind: "fishCount", fishName: "シーラカンス" },
    { id: "starWhale2", label: "ホシクジラを2匹釣る", target: 2, reward: 7600, kind: "fishCount", fishName: "ホシクジラ" },
    { id: "timeFish1", label: "トキノサカナを1匹釣る", target: 1, reward: 12000, kind: "fishCount", fishName: "トキノサカナ" },
    { id: "discover20", label: "図鑑を20種埋める", target: 20, reward: 5200, kind: "discovered" },
    { id: "discoverAll", label: "図鑑を全種埋める", target: 26, reward: 16000, kind: "discovered" },
    { id: "sizeComp10", label: "サイズコンプを10種達成", target: 10, reward: 7200, kind: "sizeComplete" },
    { id: "sizeComp20", label: "サイズコンプを20種達成", target: 20, reward: 18000, kind: "sizeComplete" },
    { id: "sizeCompAll", label: "全魚サイズコンプ", target: 26, reward: 40000, kind: "sizeComplete" },
    { id: "abyssLegends", label: "深淵三幻をすべて釣る", target: 3, reward: 22000, kind: "fishSet", fishNames: ["ホシクジラ", "アビスドラゴン", "トキノサカナ"] },
    { id: "allSsr", label: "レジェンダリー以上を全種類釣る", target: 9, reward: 30000, kind: "fishSet", fishNames: ["ニジイロギョ", "ヌシ", "コダマウオ", "ネコギョ", "シーラカンス", "リュウグウノツカイ", "ホシクジラ", "アビスドラゴン", "トキノサカナ"] },
    { id: "shiny1", label: "色違いを1匹釣る", target: 1, reward: 4096, kind: "shinyCount" },
    { id: "shiny3", label: "色違いを3匹釣る", target: 3, reward: 12288, kind: "shinyCount" },
  ],
  fishTypes: [
    { name: "ワカサギ", points: 10, shadow: 30, speed: 96, biteWindow: 0.92, color: "#dce8ec", image: "assets/fish/001.png", rarity: "COMMON", catchWeight: 32, catchDifficulty: 0, description: "群れで泳ぐ小さな魚じゃ。動きは素直で、釣りの入り口にぴったりじゃな。", recommendedSpot: "pier", sizeHint: "小と中が多く、特大はかなり珍しいぞい。" },
    { name: "アジ", points: 20, shadow: 42, speed: 82, biteWindow: 0.82, color: "#87b8d6", image: "assets/fish/002.png", rarity: "COMMON", catchWeight: 28, catchDifficulty: 0, description: "きびきびと泳ぐ元気者じゃ。桟橋まわりで姿を見せやすく、数も狙いやすいぞい。", recommendedSpot: "pier", sizeHint: "中が中心じゃが、大もそこそこ混ざる魚じゃ。" },
    { name: "タイ", points: 45, shadow: 58, speed: 68, biteWindow: 0.72, color: "#f17a73", image: "assets/fish/003.png", rarity: "UNCOMMON", catchWeight: 18, catchDifficulty: 1, description: "堂々とした魚影が目を引く一匹じゃ。焦らず合わせると、きれいに釣り上がるぞい。", recommendedSpot: "reef", sizeHint: "中と大が狙い目で、特大は岩場で望みが高まるのう。" },
    { name: "スズキ", points: 70, shadow: 76, speed: 58, biteWindow: 0.62, color: "#9fc5ba", image: "assets/fish/011.png", rarity: "RARE", catchWeight: 14, catchDifficulty: 1, description: "水面近くを鋭く回ることもある古参の大物じゃ。見えたら気を引き締めたいのう。", recommendedSpot: "reef", sizeHint: "大がよく似合う魚じゃ。特大を狙うなら岩場通いじゃな。" },
    { name: "マグロ", points: 110, shadow: 98, speed: 48, biteWindow: 0.54, color: "#4c73b8", image: "assets/fish/012.png", rarity: "EPIC", catchWeight: 7, catchDifficulty: 2, description: "海の王者と呼びたくなる迫力じゃ。浮きが沈んだ瞬間を逃さぬ者だけが手にできるぞい。", recommendedSpot: "deep", sizeHint: "大と特大の夢がある魚じゃ。深い海でこそ本領発揮じゃぞ。" },
    { name: "カワハギ", points: 65, shadow: 70, speed: 60, biteWindow: 0.66, color: "#167988", image: "assets/fish/004.png", rarity: "UNCOMMON", catchWeight: 13, catchDifficulty: 1, description: "ひらりと方向を変える身軽な魚じゃ。見た目よりも、間の取り方が勝負どころじゃな。", recommendedSpot: "reef", sizeHint: "小から大まで幅広いが、中サイズがいちばん落ち着くのう。" },
    { name: "マンボウ", points: 90, shadow: 88, speed: 42, biteWindow: 0.58, color: "#f7cbd8", image: "assets/fish/005.png", rarity: "EPIC", catchWeight: 6, catchDifficulty: 2, description: "ゆったり見えて、意外と気まぐれ。大きな魚影のわりに、出会えると少しうれしくなる魚じゃ。", recommendedSpot: "deep", sizeHint: "中でも大きく見えるが、真の狙いは大と特大じゃな。" },
    { name: "ニジイロギョ", points: 150, shadow: 92, speed: 62, biteWindow: 0.5, color: "#ff5eb8", image: "assets/fish/006.png", rarity: "LEGENDARY", catchWeight: 4, catchDifficulty: 3, description: "光の加減で色が揺れるように見える珍魚じゃ。見つけても、落ち着いて狙わねば逃げるぞい。", recommendedSpot: "deep", sizeHint: "中以上が多く、特大はひときわ華やかな記録になるぞい。" },
    { name: "ヌシ", points: 220, shadow: 104, speed: 38, biteWindow: 0.44, color: "#347d9f", image: "assets/fish/007.png", rarity: "LEGENDARY", catchWeight: 1, catchDifficulty: 3, description: "その場の空気まで変える特別な魚影じゃ。釣れたなら、胸を張って自慢してよいぞい。", recommendedSpot: "deep", sizeHint: "大物ぞろいじゃ。特大の記録は、まさに語り草になるじゃろう。" },
    { name: "ハートフィッシュ", points: 85, shadow: 72, speed: 70, biteWindow: 0.64, color: "#c9f0e8", image: "assets/fish/008.png", rarity: "UNCOMMON", catchWeight: 10, catchDifficulty: 1, description: "愛らしい模様をもつ人気者じゃ。近づき方は素直じゃが、見とれておると機を逃すのう。", recommendedSpot: "estuary", sizeHint: "小と中を集めやすい魚じゃ。大になると急に出会いが減るぞい。" },
    { name: "ムーンフィッシュ", points: 140, shadow: 90, speed: 56, biteWindow: 0.52, color: "#6d67b8", image: "assets/fish/009.png", rarity: "EPIC", catchWeight: 5, catchDifficulty: 2, description: "夜の海を思わせる静かな気配をまとう魚じゃ。落ち着いて待てる者ほど縁があるぞい。", recommendedSpot: "deep", sizeHint: "中から大が中心じゃが、特大はめったに姿を見せぬのう。" },
    { name: "コダマウオ", points: 185, shadow: 86, speed: 66, biteWindow: 0.46, color: "#d9d7f8", image: "assets/fish/010.png", rarity: "MYTHIC", catchWeight: 2, catchDifficulty: 3, description: "魚なのか精霊なのか、博士にも断言できぬ不思議な存在じゃ。見つけたら幸運と思ってよい。", recommendedSpot: "deep", sizeHint: "中以上で現れやすく、特大は本当に気まぐれじゃ。" },
    { name: "タコ", points: 75, shadow: 68, speed: 64, biteWindow: 0.68, color: "#f3a5be", image: "assets/fish/013.png", rarity: "UNCOMMON", catchWeight: 11, catchDifficulty: 1, description: "泳ぎ方が独特で、影の見え方も少し変わっておる。海の変化球として侮れぬ相手じゃ。", recommendedSpot: "reef", sizeHint: "中サイズが集まりやすいが、大も十分狙える手応えがあるぞい。" },
    { name: "ネコギョ", points: 190, shadow: 94, speed: 54, biteWindow: 0.46, color: "#f3c28d", image: "assets/fish/014.png", rarity: "MYTHIC", catchWeight: 2, catchDifficulty: 3, description: "見た者の多くが二度見する珍魚じゃ。魚らしさと猫らしさ、その両方を感じる妙味があるのう。", recommendedSpot: "pier", sizeHint: "小でも存在感があるが、大と特大はとくに記憶に残る釣果じゃ。" },
    { name: "イワシ", points: 14, shadow: 34, speed: 92, biteWindow: 0.88, color: "#b8d8e6", image: "assets/fish/015.png", rarity: "COMMON", catchWeight: 30, catchDifficulty: 0, description: "小さな銀色の魚じゃ。数は多いが、サイズを揃えようとすると意外に奥深いぞい。", recommendedSpot: "estuary", sizeHint: "小と中が中心じゃ。特大は河口でもかなり根気がいるのう。" },
    { name: "サバ", points: 26, shadow: 48, speed: 78, biteWindow: 0.78, color: "#5f91b5", image: "assets/fish/016.png", rarity: "COMMON", catchWeight: 24, catchDifficulty: 0, description: "よく走る青い魚じゃ。序盤の稼ぎ役として頼れるが、大物狙いでは油断禁物じゃ。", recommendedSpot: "pier", sizeHint: "中が多く、大もそこそこ混ざる。特大は回数勝負じゃな。" },
    { name: "カレイ", points: 32, shadow: 54, speed: 70, biteWindow: 0.76, color: "#c9a56c", image: "assets/fish/017.png", rarity: "UNCOMMON", catchWeight: 20, catchDifficulty: 0, description: "底のほうにじっと構える魚じゃ。派手ではないが、図鑑埋めでは頼もしい一匹じゃ。", recommendedSpot: "reef", sizeHint: "小から大まで幅広い。岩場で大きめを狙いやすいぞい。" },
    { name: "サンゴウオ", points: 82, shadow: 64, speed: 66, biteWindow: 0.62, color: "#ff8f77", image: "assets/fish/018.png", rarity: "RARE", catchWeight: 9, catchDifficulty: 1, description: "岩場の色にまぎれる鮮やかな魚じゃ。見つけたら、影の動きをよく読むのじゃ。", recommendedSpot: "reef", sizeHint: "中と大が多い。特大は岩場で粘る価値ありじゃ。" },
    { name: "トビウオ", points: 88, shadow: 62, speed: 86, biteWindow: 0.56, color: "#74c7e8", image: "assets/fish/019.png", rarity: "RARE", catchWeight: 8, catchDifficulty: 1, description: "勢いよく水面近くを走る魚じゃ。反応は速め、合わせは迷わぬことじゃな。", recommendedSpot: "reef", sizeHint: "小と中が多いが、まれに大きな影で飛び込んでくるぞい。" },
    { name: "ヤドカリウオ", points: 96, shadow: 60, speed: 58, biteWindow: 0.6, color: "#d89052", image: "assets/fish/020.png", rarity: "RARE", catchWeight: 7, catchDifficulty: 1, description: "魚か貝か少し悩む不思議な相手じゃ。独特の間でつつくので焦りは禁物じゃ。", recommendedSpot: "reef", sizeHint: "小さめが多い。サイズコンプには根気がいる魚じゃ。" },
    { name: "オウムガイ", points: 165, shadow: 84, speed: 50, biteWindow: 0.5, color: "#ead0a2", image: "assets/fish/021.png", rarity: "EPIC", catchWeight: 4, catchDifficulty: 2, description: "古い海の記憶を背負ったような魚影じゃ。深い海で静かに待つと出会いやすいぞい。", recommendedSpot: "deep", sizeHint: "中と大が中心。特大は深い海でもかなり珍しいのう。" },
    { name: "シーラカンス", points: 210, shadow: 102, speed: 44, biteWindow: 0.44, color: "#4e6d7a", image: "assets/fish/022.png", rarity: "LEGENDARY", catchWeight: 3, catchDifficulty: 3, description: "生きた化石と呼びたい重みのある魚じゃ。影が大きくても、合わせは繊細にいくのじゃ。", recommendedSpot: "abyss", sizeHint: "大と特大の夢が大きい魚じゃ。幻の海溝で狙うのが近道じゃな。" },
    { name: "リュウグウノツカイ", points: 320, shadow: 114, speed: 40, biteWindow: 0.38, color: "#dfe8ff", rarity: "MYTHIC", catchWeight: 1.3, catchDifficulty: 4, description: "長い影がすっと横切る、海の奥からの使者じゃ。終盤装備でも油断ならぬぞい。", recommendedSpot: "abyss", sizeHint: "大以上で現れることが多い。特大はまさしく大記録じゃ。" },
    { name: "ホシクジラ", points: 420, shadow: 128, speed: 34, biteWindow: 0.34, color: "#3f4ea8", rarity: "MYTHIC", catchWeight: 0.9, catchDifficulty: 4, description: "夜空を背負って泳ぐような巨大な魚影じゃ。出会いそのものが冒険の証じゃな。", recommendedSpot: "abyss", sizeHint: "大と特大が本命じゃ。小さめでも価値は十分すぎるほどあるぞい。" },
    { name: "アビスドラゴン", points: 520, shadow: 136, speed: 32, biteWindow: 0.32, color: "#7d4df2", rarity: "SECRET", catchWeight: 0.65, catchDifficulty: 4, description: "深淵の名を持つ、最難関級の魚じゃ。浮きが沈んだ瞬間、迷いは置いていくのじゃ。", recommendedSpot: "abyss", sizeHint: "特大は伝説級じゃ。装備とフィーバーを重ねて挑むのがよい。" },
    { name: "トキノサカナ", points: 800, shadow: 92, speed: 72, biteWindow: 0.28, color: "#fff08a", rarity: "SECRET", catchWeight: 0.28, catchDifficulty: 4, description: "一瞬だけ時間が止まったように見える幻魚じゃ。博士もまだ一度しか見ておらん。", recommendedSpot: "abyss", sizeHint: "サイズ以前に出会うことが難しい魚じゃ。全サイズ制覇は長い旅になるぞい。" },
  ],
});
